#!/bin/sh

rsync -rav --delete \
	--exclude '.*' --exclude node_modules \
	. 'root@tip-me.org:~/tip-www/'

ssh 'root@tip-me.org' "\
cd ~/tip-www
npm i
export NODE_ENV=production
forever stop tip-www
forever start -a --uid tip-www index.js"
